version: '2'

networks:
 app-tier:
  driver: bridge


services:
 zoo1:
  image: wurstmeister/zookeeper:3.4.6
  privileged: true
 kafka1:
   build: kafka
   privileged: true
   links:
    - zoo1
   environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_CREATE_TOPICS: "THE.TEST:20:2"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
 
 cassandra1:
  image: cassandra:latest
  privileged: true
  volumes:
   - /home/ankita/cassandra:/cassandra
  ports:
   - "9042:9042"
  networks:
   - app-tier
